"""
CosmicWatch - Synthetic Demonstration Data Generator.

SCIENTIFIC DISCLAIMER:
Synthetic signals generated by this module are controlled artificial signals
designed strictly for unit testing, algorithm benchmarking, and offline hackathon demonstration.
They DO NOT represent extraterrestrial transmissions or genuine astronomical discoveries.
"""

from typing import Tuple, Optional, Dict, Any, List
import numpy as np
from ml.preprocessing.waterfall import WaterfallWindow
from ml.preprocessing.normalize import robust_percentile_norm


class SyntheticSignalGenerator:
    """
    Generates reproducible synthetic radio spectrogram windows with realistic
    receiver noise, baseline ripple, and optional injected signal signatures.
    """

    SIGNAL_TYPES = [
        "NORMAL_NOISE",
        "NARROWBAND",
        "DRIFTING_NARROWBAND",
        "INTERMITTENT",
        "BROADBAND_BURST",
        "TERRESTRIAL_RFI",
    ]

    def __init__(self, time_steps: int = 16, freq_channels: int = 256, seed: int = 42):
        self.time_steps = time_steps
        self.freq_channels = freq_channels
        self.rng = np.random.default_rng(seed)

    def _generate_background_noise(self) -> np.ndarray:
        """
        Creates realistic radio telescope background:
        Gaussian thermal receiver noise + parabolic bandpass shape across channels.
        """
        # Gaussian white noise
        noise = self.rng.normal(loc=1.0, scale=0.15, size=(self.time_steps, self.freq_channels))
        # Add smooth bandpass baseline shape
        x = np.linspace(-1.0, 1.0, self.freq_channels)
        bandpass = 1.0 - 0.25 * (x ** 2)
        noise = noise * bandpass[np.newaxis, :]
        return np.clip(noise, 0.01, None)

    def generate_sample(
        self,
        signal_type: str = "NORMAL_NOISE",
        snr_db: float = 12.0,
        observation_id: Optional[str] = None,
        target_name: str = "SYNTHETIC-TARGET",
        telescope: str = "GBT",
        seed: Optional[int] = None
    ) -> WaterfallWindow:
        """
        Generates a WaterfallWindow with the specified signal profile.
        """
        if seed is not None:
            self.rng = np.random.default_rng(seed)

        data = self._generate_background_noise()
        linear_snr = 10.0 ** (snr_db / 10.0)
        signal_power = float(np.mean(data)) * linear_snr * 0.15

        if signal_type == "NORMAL_NOISE":
            pass

        elif signal_type == "NARROWBAND":
            # Stationary narrow carrier in a single frequency channel
            center_bin = int(self.rng.integers(int(self.freq_channels * 0.3), int(self.freq_channels * 0.7)))
            data[:, center_bin] += signal_power * self.rng.normal(1.0, 0.05, size=self.time_steps)
            if center_bin + 1 < self.freq_channels:
                data[:, center_bin + 1] += 0.3 * signal_power
            if center_bin - 1 >= 0:
                data[:, center_bin - 1] += 0.3 * signal_power

        elif signal_type == "DRIFTING_NARROWBAND":
            # Linear Doppler frequency drift across time steps
            start_bin = float(self.rng.integers(int(self.freq_channels * 0.35), int(self.freq_channels * 0.65)))
            drift_rate = float(self.rng.choice([-1.2, -0.8, -0.5, 0.5, 0.8, 1.2]))  # bins per time step
            for t in range(self.time_steps):
                curr_bin = int(round(start_bin + t * drift_rate))
                if 0 <= curr_bin < self.freq_channels:
                    amp = signal_power * self.rng.normal(1.0, 0.08)
                    data[t, curr_bin] += amp
                    if curr_bin + 1 < self.freq_channels:
                        data[t, curr_bin + 1] += 0.25 * amp
                    if curr_bin - 1 >= 0:
                        data[t, curr_bin - 1] += 0.25 * amp

        elif signal_type == "INTERMITTENT":
            # Pulsed carrier with duty cycle (e.g. active for only some time integrations)
            center_bin = int(self.rng.integers(int(self.freq_channels * 0.3), int(self.freq_channels * 0.7)))
            duty_mask = (np.arange(self.time_steps) % 3 == 0) | (np.arange(self.time_steps) % 4 == 0)
            for t in range(self.time_steps):
                if duty_mask[t]:
                    data[t, center_bin] += signal_power * 1.3

        elif signal_type == "BROADBAND_BURST":
            # Short duration transient across many frequency bins
            burst_time = int(self.rng.integers(2, max(3, self.time_steps - 2)))
            f_span = int(self.freq_channels * 0.3)
            f_start = int(self.rng.integers(10, self.freq_channels - f_span - 10))
            data[burst_time, f_start : f_start + f_span] += signal_power * 0.8
            if burst_time + 1 < self.time_steps:
                data[burst_time + 1, f_start : f_start + f_span] += signal_power * 0.4

        elif signal_type == "TERRESTRIAL_RFI":
            # Continuous multi-channel interference or wideband comb
            comb_bins = [
                int(self.freq_channels * 0.2),
                int(self.freq_channels * 0.45),
                int(self.freq_channels * 0.7),
            ]
            for cb in comb_bins:
                data[:, cb] += signal_power * 1.5

        # Normalize to [0, 1]
        norm_data = robust_percentile_norm(data, p_low=1.0, p_high=99.0)

        obs_id = observation_id or f"CW-SYNTH-{self.rng.integers(1000, 9999)}"

        return WaterfallWindow(
            data=norm_data,
            source_file="synthetic_pipeline.sim",
            observation_id=obs_id,
            target_name=target_name,
            telescope=telescope,
            freq_start_mhz=1420.0,
            freq_end_mhz=1420.0 + (self.freq_channels * 2.79e-6 * 1000),
            time_start_mjd=59000.0,
            time_end_mjd=59000.0 + (self.time_steps * 18.25 / 86400.0),
            time_steps=self.time_steps,
            freq_channels=self.freq_channels,
            is_synthetic=True,
            injected_type=signal_type,
            snr_db=snr_db if signal_type != "NORMAL_NOISE" else 0.0,
            extra_metadata={
                "synthetic_notice": "Generated for testing/benchmarking. NOT an extraterrestrial discovery.",
                "algorithm": "SyntheticSignalGenerator-v1"
            }
        )

    def generate_on_off_pair(
        self,
        signal_type: str = "DRIFTING_NARROWBAND",
        is_rfi: bool = False,
        seed: Optional[int] = None
    ) -> Tuple[WaterfallWindow, WaterfallWindow]:
        """
        Generates an ON/OFF observation pair.
        - If is_rfi=False: Signal appears ONLY in the ON observation (Target).
          OFF observation (Calibrator/Off-target) has only normal noise.
          -> High investigation candidate.
        - If is_rfi=True: Signal appears in BOTH ON and OFF observations.
          -> Local terrestrial RFI.
        """
        if seed is not None:
            self.rng = np.random.default_rng(seed)

        on_window = self.generate_sample(
            signal_type=signal_type,
            snr_db=14.0,
            observation_id="CW-OBS-ON",
            target_name="TARGET-A (ON-SOURCE)",
            telescope="Green Bank Telescope"
        )

        off_signal_type = signal_type if is_rfi else "NORMAL_NOISE"
        off_window = self.generate_sample(
            signal_type=off_signal_type,
            snr_db=14.0 if is_rfi else 0.0,
            observation_id="CW-OBS-OFF",
            target_name="OFF-POINTING-B (OFF-SOURCE)",
            telescope="Green Bank Telescope"
        )

        return on_window, off_window
